import 'models.dart';

/// Generated from the archived legacy plan/ directory (legacy/simbox-desktop-v2014/var/simbox/plan09042014.tar.gz) via a
/// one-off script — see 03-specifications.md's Seed generation section.
/// The 9 audit-only ids (present in the archive, absent from plan.list)
/// are intentionally not emitted here.
const List<Plan> planSeed = [
  Plan(
    id: "default",
    commandSetId: "default",
    priority: 5,
    onlineMax: 5,
    addMax: 1,
    diffSlow: 5,
    diffMin: 120,
    iattMin: 4,
    iattMax: 15,
    iattSoft: 1,
    inAcdMin: 60,
    inAcdMax: 180,
    outAcdMin: 60,
    outAcdMax: 180,
    outInAns: 6,
    mayLimit: 5,
    monLimit: 3,
    msmLimit: 1,
    smsoutSoft: 0,
    smsoutHard: 1,
    sattSoft: 10,
    sattHard: 50,
    sattSoftDay: 10,
    sattHardDay: 3,
    sattSoftTotal: 100,
    sattHardTotal: 20,
    nospam: 1,
    canIn: true,
    canOut: true,
    canSout: true,
    notVip: true,
    capOk: true,
    capNew: true,
    capFail: false,
    forwarding: true,
    conn: true,
    rand: true,
    inWait: false,
    inSound: true,
    qualityFlags: {"VIP", "GOO", "NOR", "BAD", "NEW"},
    directions: [
      DirectionSlot(
          slot: 0,
          editable: false,
          alg: 0,
          nodiff: false,
          limitSoft: 0,
          limitHard: 0),
      DirectionSlot(
          slot: 1,
          editable: true,
          alg: 42,
          nodiff: true,
          limitSoft: 1,
          limitHard: 2),
      DirectionSlot(
          slot: 2,
          editable: true,
          alg: 42,
          nodiff: true,
          limitSoft: 9000,
          limitHard: 10000),
      DirectionSlot(
          slot: 3,
          editable: true,
          alg: 42,
          nodiff: false,
          limitSoft: 5,
          limitHard: 4),
      DirectionSlot(
          slot: 4,
          editable: true,
          alg: 42,
          nodiff: true,
          limitSoft: 7,
          limitHard: 5),
      DirectionSlot(
          slot: 5,
          editable: false,
          alg: 0,
          nodiff: false,
          limitSoft: 0,
          limitHard: 0)
    ],
  ),
  Plan(
    id: "tele2_spb_good",
    commandSetId: "tele2_spb",
    priority: 6,
    onlineMax: 5,
    addMax: 1,
    diffSlow: 5,
    diffMin: 21,
    iattMin: 999,
    iattMax: 999,
    iattSoft: 1,
    inAcdMin: 60,
    inAcdMax: 180,
    outAcdMin: 60,
    outAcdMax: 180,
    outInAns: 5,
    mayLimit: 0,
    monLimit: 4,
    msmLimit: 0,
    smsoutSoft: 50,
    smsoutHard: 90,
    sattSoft: 10,
    sattHard: 50,
    sattSoftDay: 10,
    sattHardDay: 90,
    sattSoftTotal: 100,
    sattHardTotal: 95,
    nospam: 2,
    canIn: true,
    canOut: true,
    canSout: true,
    notVip: true,
    capOk: true,
    capNew: true,
    capFail: true,
    forwarding: true,
    conn: true,
    rand: true,
    inWait: false,
    inSound: true,
    qualityFlags: {"VIP", "GOO", "NOR", "NEW", "NOS"},
    directions: [
      DirectionSlot(
          slot: 0,
          editable: false,
          alg: 0,
          nodiff: false,
          limitSoft: 0,
          limitHard: 0),
      DirectionSlot(
          slot: 1,
          editable: true,
          alg: 98,
          nodiff: true,
          limitSoft: 9000,
          limitHard: 10000),
      DirectionSlot(
          slot: 2,
          editable: true,
          alg: 60,
          nodiff: false,
          limitSoft: 9000,
          limitHard: 10000),
      DirectionSlot(
          slot: 3,
          editable: true,
          alg: 60,
          nodiff: false,
          limitSoft: 9000,
          limitHard: 0),
      DirectionSlot(
          slot: 4,
          editable: true,
          alg: 97,
          nodiff: false,
          limitSoft: 0,
          limitHard: 0),
      DirectionSlot(
          slot: 5,
          editable: false,
          alg: 0,
          nodiff: false,
          limitSoft: 0,
          limitHard: 0)
    ],
  ),
  Plan(
    id: "tele2_spb_max",
    commandSetId: "tele2_spb",
    proTag: "2",
    priority: 8,
    onlineMax: 5,
    addMax: 1,
    diffSlow: 5,
    diffMin: 21,
    iattMin: 999,
    iattMax: 999,
    iattSoft: 1,
    inAcdMin: 60,
    inAcdMax: 180,
    outAcdMin: 60,
    outAcdMax: 180,
    outInAns: 6,
    mayLimit: 0,
    monLimit: 4,
    msmLimit: 0,
    smsoutSoft: 50,
    smsoutHard: 95,
    sattSoft: 10,
    sattHard: 50,
    sattSoftDay: 10,
    sattHardDay: 90,
    sattSoftTotal: 100,
    sattHardTotal: 95,
    nospam: 2,
    canIn: true,
    canOut: true,
    canSout: true,
    notVip: true,
    capOk: true,
    capNew: true,
    capFail: true,
    forwarding: true,
    conn: false,
    rand: true,
    inWait: false,
    inSound: true,
    qualityFlags: {"VIP", "GOO", "NOR", "BAD", "NEW", "NOS", "BLO"},
    directions: [
      DirectionSlot(
          slot: 0,
          editable: false,
          alg: 0,
          nodiff: false,
          limitSoft: 0,
          limitHard: 0),
      DirectionSlot(
          slot: 1,
          editable: true,
          alg: 98,
          nodiff: true,
          limitSoft: 9000,
          limitHard: 10000),
      DirectionSlot(
          slot: 2,
          editable: true,
          alg: 80,
          nodiff: false,
          limitSoft: 9000,
          limitHard: 10000),
      DirectionSlot(
          slot: 3,
          editable: true,
          alg: 80,
          nodiff: false,
          limitSoft: 0,
          limitHard: 10000),
      DirectionSlot(
          slot: 4,
          editable: true,
          alg: 80,
          nodiff: false,
          limitSoft: 9000,
          limitHard: 0),
      DirectionSlot(
          slot: 5,
          editable: false,
          alg: 0,
          nodiff: false,
          limitSoft: 0,
          limitHard: 0)
    ],
  ),
  Plan(
    id: "tele2_trash",
    commandSetId: "tele2_spb",
    priority: 2,
    onlineMax: 5,
    addMax: 1,
    diffSlow: 5,
    diffMin: 12,
    iattMin: 999,
    iattMax: 15,
    iattSoft: 1,
    inAcdMin: 60,
    inAcdMax: 180,
    outAcdMin: 60,
    outAcdMax: 180,
    outInAns: 6,
    mayLimit: 5,
    monLimit: 2,
    msmLimit: 1,
    smsoutSoft: 50,
    smsoutHard: 95,
    sattSoft: 10,
    sattHard: 50,
    sattSoftDay: 10,
    sattHardDay: 90,
    sattSoftTotal: 100,
    sattHardTotal: 95,
    nospam: 2,
    canIn: true,
    canOut: true,
    canSout: true,
    notVip: true,
    capOk: true,
    capNew: true,
    capFail: true,
    forwarding: true,
    conn: false,
    rand: false,
    inWait: false,
    inSound: false,
    qualityFlags: {"VIP", "NEW", "NOS"},
    directions: [
      DirectionSlot(
          slot: 0,
          editable: false,
          alg: 0,
          nodiff: false,
          limitSoft: 0,
          limitHard: 0),
      DirectionSlot(
          slot: 1,
          editable: true,
          alg: 66,
          nodiff: false,
          limitSoft: 9000,
          limitHard: 10000),
      DirectionSlot(
          slot: 2,
          editable: true,
          alg: 68,
          nodiff: false,
          limitSoft: 9000,
          limitHard: 10000),
      DirectionSlot(
          slot: 3,
          editable: true,
          alg: 68,
          nodiff: false,
          limitSoft: 9000,
          limitHard: 10000),
      DirectionSlot(
          slot: 4,
          editable: true,
          alg: 65,
          nodiff: false,
          limitSoft: 9000,
          limitHard: 10000),
      DirectionSlot(
          slot: 5,
          editable: false,
          alg: 0,
          nodiff: false,
          limitSoft: 0,
          limitHard: 0)
    ],
  ),
  Plan(
    id: "tele2_sms",
    commandSetId: "tele2_spb",
    priority: 2,
    onlineMax: 5,
    addMax: 5,
    diffSlow: 5,
    diffMin: 12,
    iattMin: 999,
    iattMax: 15,
    iattSoft: 1,
    inAcdMin: 60,
    inAcdMax: 180,
    outAcdMin: 60,
    outAcdMax: 180,
    outInAns: 6,
    mayLimit: 5,
    monLimit: 2,
    msmLimit: 1,
    smsoutSoft: 50,
    smsoutHard: 95,
    sattSoft: 10,
    sattHard: 50,
    sattSoftDay: 10,
    sattHardDay: 90,
    sattSoftTotal: 100,
    sattHardTotal: 95,
    nospam: 2,
    canIn: true,
    canOut: true,
    canSout: true,
    notVip: true,
    capOk: true,
    capNew: true,
    capFail: true,
    forwarding: true,
    conn: false,
    rand: false,
    inWait: false,
    inSound: false,
    qualityFlags: {"VIP", "NEW", "NOS"},
    directions: [
      DirectionSlot(
          slot: 0,
          editable: false,
          alg: 0,
          nodiff: false,
          limitSoft: 0,
          limitHard: 0),
      DirectionSlot(
          slot: 1,
          editable: true,
          alg: 66,
          nodiff: false,
          limitSoft: 9000,
          limitHard: 10000),
      DirectionSlot(
          slot: 2,
          editable: true,
          alg: 68,
          nodiff: false,
          limitSoft: 9000,
          limitHard: 10000),
      DirectionSlot(
          slot: 3,
          editable: true,
          alg: 68,
          nodiff: false,
          limitSoft: 9000,
          limitHard: 10000),
      DirectionSlot(
          slot: 4,
          editable: true,
          alg: 65,
          nodiff: false,
          limitSoft: 9000,
          limitHard: 10000),
      DirectionSlot(
          slot: 5,
          editable: false,
          alg: 0,
          nodiff: false,
          limitSoft: 0,
          limitHard: 0)
    ],
  ),
  Plan(
    id: "beeline_spb_vip",
    commandSetId: "beeline_spb",
    priority: 9,
    onlineMax: 5,
    addMax: 1,
    diffSlow: 20,
    diffMin: 1000,
    iattMin: 3,
    iattMax: 8,
    iattSoft: 1,
    inAcdMin: 120,
    inAcdMax: 240,
    outAcdMin: 120,
    outAcdMax: 240,
    outInAns: 6,
    mayLimit: 5,
    monLimit: 3,
    msmLimit: 1,
    smsoutSoft: 10,
    smsoutHard: 50,
    sattSoft: 10,
    sattHard: 50,
    sattSoftDay: 10,
    sattHardDay: 3,
    sattSoftTotal: 100,
    sattHardTotal: 20,
    nospam: 1,
    canIn: true,
    canOut: true,
    canSout: true,
    notVip: true,
    capOk: true,
    capNew: true,
    capFail: true,
    forwarding: true,
    conn: true,
    rand: true,
    inWait: false,
    inSound: true,
    qualityFlags: {"VIP", "GOO"},
    directions: [
      DirectionSlot(
          slot: 0,
          editable: false,
          alg: 0,
          nodiff: false,
          limitSoft: 0,
          limitHard: 0),
      DirectionSlot(
          slot: 1,
          editable: true,
          alg: 68,
          nodiff: false,
          limitSoft: 9000,
          limitHard: 10000),
      DirectionSlot(
          slot: 2,
          editable: true,
          alg: 68,
          nodiff: false,
          limitSoft: 9000,
          limitHard: 10000),
      DirectionSlot(
          slot: 3,
          editable: true,
          alg: 68,
          nodiff: false,
          limitSoft: 9000,
          limitHard: 10000),
      DirectionSlot(
          slot: 4,
          editable: true,
          alg: 68,
          nodiff: false,
          limitSoft: 9000,
          limitHard: 10000),
      DirectionSlot(
          slot: 5,
          editable: false,
          alg: 0,
          nodiff: false,
          limitSoft: 0,
          limitHard: 0)
    ],
  ),
  Plan(
    id: "beeline_spb_good",
    commandSetId: "beeline_spb",
    priority: 8,
    onlineMax: 5,
    addMax: 1,
    diffSlow: 20,
    diffMin: 1000,
    iattMin: 3,
    iattMax: 8,
    iattSoft: 1,
    inAcdMin: 120,
    inAcdMax: 240,
    outAcdMin: 120,
    outAcdMax: 240,
    outInAns: 6,
    mayLimit: 5,
    monLimit: 3,
    msmLimit: 1,
    smsoutSoft: 1,
    smsoutHard: 1,
    sattSoft: 10,
    sattHard: 50,
    sattSoftDay: 10,
    sattHardDay: 3,
    sattSoftTotal: 100,
    sattHardTotal: 20,
    nospam: 1,
    canIn: true,
    canOut: true,
    canSout: true,
    notVip: true,
    capOk: true,
    capNew: true,
    capFail: true,
    forwarding: true,
    conn: true,
    rand: true,
    inWait: false,
    inSound: true,
    qualityFlags: {"VIP", "GOO", "NOR"},
    directions: [
      DirectionSlot(
          slot: 0,
          editable: false,
          alg: 0,
          nodiff: false,
          limitSoft: 0,
          limitHard: 0),
      DirectionSlot(
          slot: 1,
          editable: true,
          alg: 68,
          nodiff: false,
          limitSoft: 9000,
          limitHard: 10000),
      DirectionSlot(
          slot: 2,
          editable: true,
          alg: 68,
          nodiff: false,
          limitSoft: 9000,
          limitHard: 10000),
      DirectionSlot(
          slot: 3,
          editable: true,
          alg: 68,
          nodiff: false,
          limitSoft: 9000,
          limitHard: 10000),
      DirectionSlot(
          slot: 4,
          editable: true,
          alg: 68,
          nodiff: false,
          limitSoft: 9000,
          limitHard: 10000),
      DirectionSlot(
          slot: 5,
          editable: false,
          alg: 0,
          nodiff: false,
          limitSoft: 0,
          limitHard: 0)
    ],
  ),
  Plan(
    id: "beeline_spb_normal",
    commandSetId: "beeline_spb",
    priority: 7,
    onlineMax: 5,
    addMax: 1,
    diffSlow: 20,
    diffMin: 1000,
    iattMin: 3,
    iattMax: 8,
    iattSoft: 1,
    inAcdMin: 120,
    inAcdMax: 240,
    outAcdMin: 120,
    outAcdMax: 240,
    outInAns: 6,
    mayLimit: 5,
    monLimit: 3,
    msmLimit: 1,
    smsoutSoft: 1,
    smsoutHard: 1,
    sattSoft: 10,
    sattHard: 50,
    sattSoftDay: 10,
    sattHardDay: 3,
    sattSoftTotal: 100,
    sattHardTotal: 20,
    nospam: 1,
    canIn: true,
    canOut: true,
    canSout: true,
    notVip: true,
    capOk: true,
    capNew: true,
    capFail: false,
    forwarding: true,
    conn: true,
    rand: true,
    inWait: false,
    inSound: true,
    qualityFlags: {"VIP", "GOO", "NOR"},
    directions: [
      DirectionSlot(
          slot: 0,
          editable: false,
          alg: 0,
          nodiff: false,
          limitSoft: 0,
          limitHard: 0),
      DirectionSlot(
          slot: 1,
          editable: true,
          alg: 68,
          nodiff: false,
          limitSoft: 9000,
          limitHard: 10000),
      DirectionSlot(
          slot: 2,
          editable: true,
          alg: 68,
          nodiff: false,
          limitSoft: 9000,
          limitHard: 10000),
      DirectionSlot(
          slot: 3,
          editable: true,
          alg: 68,
          nodiff: false,
          limitSoft: 9000,
          limitHard: 10000),
      DirectionSlot(
          slot: 4,
          editable: true,
          alg: 68,
          nodiff: false,
          limitSoft: 9000,
          limitHard: 10000),
      DirectionSlot(
          slot: 5,
          editable: false,
          alg: 0,
          nodiff: false,
          limitSoft: 0,
          limitHard: 0)
    ],
  ),
  Plan(
    id: "beeline_spb_main",
    commandSetId: "beeline_spb",
    priority: 6,
    onlineMax: 20,
    addMax: 5,
    diffSlow: 20,
    diffMin: 1000,
    iattMin: 3,
    iattMax: 8,
    iattSoft: 1,
    inAcdMin: 120,
    inAcdMax: 240,
    outAcdMin: 120,
    outAcdMax: 240,
    outInAns: 6,
    mayLimit: 5,
    monLimit: 3,
    msmLimit: 1,
    smsoutSoft: 0,
    smsoutHard: 1,
    sattSoft: 10,
    sattHard: 50,
    sattSoftDay: 10,
    sattHardDay: 3,
    sattSoftTotal: 100,
    sattHardTotal: 20,
    nospam: 1,
    canIn: true,
    canOut: true,
    canSout: true,
    notVip: true,
    capOk: true,
    capNew: true,
    capFail: true,
    forwarding: true,
    conn: true,
    rand: true,
    inWait: false,
    inSound: true,
    qualityFlags: {"VIP", "GOO", "NOR"},
    directions: [
      DirectionSlot(
          slot: 0,
          editable: false,
          alg: 0,
          nodiff: false,
          limitSoft: 0,
          limitHard: 0),
      DirectionSlot(
          slot: 1,
          editable: true,
          alg: 68,
          nodiff: false,
          limitSoft: 9000,
          limitHard: 10000),
      DirectionSlot(
          slot: 2,
          editable: true,
          alg: 68,
          nodiff: false,
          limitSoft: 9000,
          limitHard: 10000),
      DirectionSlot(
          slot: 3,
          editable: true,
          alg: 68,
          nodiff: false,
          limitSoft: 9000,
          limitHard: 10000),
      DirectionSlot(
          slot: 4,
          editable: true,
          alg: 68,
          nodiff: false,
          limitSoft: 9000,
          limitHard: 10000),
      DirectionSlot(
          slot: 5,
          editable: false,
          alg: 0,
          nodiff: false,
          limitSoft: 0,
          limitHard: 0)
    ],
  ),
  Plan(
    id: "beeline_spb_bad",
    commandSetId: "beeline_spb",
    priority: 5,
    onlineMax: 5,
    addMax: 1,
    diffSlow: 20,
    diffMin: 1000,
    iattMin: 3,
    iattMax: 8,
    iattSoft: 1,
    inAcdMin: 120,
    inAcdMax: 240,
    outAcdMin: 120,
    outAcdMax: 240,
    outInAns: 6,
    mayLimit: 5,
    monLimit: 3,
    msmLimit: 1,
    smsoutSoft: 95,
    smsoutHard: 95,
    sattSoft: 10,
    sattHard: 50,
    sattSoftDay: 10,
    sattHardDay: 95,
    sattSoftTotal: 100,
    sattHardTotal: 95,
    nospam: 2,
    canIn: true,
    canOut: true,
    canSout: true,
    notVip: true,
    capOk: true,
    capNew: true,
    capFail: true,
    forwarding: true,
    conn: true,
    rand: true,
    inWait: false,
    inSound: true,
    qualityFlags: {"VIP", "GOO", "NOR"},
    directions: [
      DirectionSlot(
          slot: 0,
          editable: false,
          alg: 0,
          nodiff: false,
          limitSoft: 0,
          limitHard: 0),
      DirectionSlot(
          slot: 1,
          editable: true,
          alg: 68,
          nodiff: false,
          limitSoft: 9000,
          limitHard: 10000),
      DirectionSlot(
          slot: 2,
          editable: true,
          alg: 68,
          nodiff: false,
          limitSoft: 9000,
          limitHard: 10000),
      DirectionSlot(
          slot: 3,
          editable: true,
          alg: 68,
          nodiff: false,
          limitSoft: 9000,
          limitHard: 10000),
      DirectionSlot(
          slot: 4,
          editable: true,
          alg: 68,
          nodiff: false,
          limitSoft: 9000,
          limitHard: 10000),
      DirectionSlot(
          slot: 5,
          editable: false,
          alg: 0,
          nodiff: false,
          limitSoft: 0,
          limitHard: 0)
    ],
  ),
  Plan(
    id: "megafon_spb_vip",
    commandSetId: "megafon_spb",
    priority: 8,
    onlineMax: 5,
    addMax: 1,
    diffSlow: 5,
    diffMin: 61,
    iattMin: 5,
    iattMax: 20,
    iattSoft: 1,
    inAcdMin: 180,
    inAcdMax: 240,
    outAcdMin: 180,
    outAcdMax: 240,
    outInAns: 10,
    mayLimit: 5,
    monLimit: 2,
    msmLimit: 1,
    smsoutSoft: 0,
    smsoutHard: 1,
    sattSoft: 10,
    sattHard: 50,
    sattSoftDay: 10,
    sattHardDay: 3,
    sattSoftTotal: 100,
    sattHardTotal: 20,
    nospam: 1,
    canIn: true,
    canOut: true,
    canSout: true,
    notVip: true,
    capOk: true,
    capNew: true,
    capFail: false,
    forwarding: true,
    conn: true,
    rand: true,
    inWait: false,
    inSound: true,
    qualityFlags: {"VIP", "GOO", "NOR", "NEW"},
    directions: [
      DirectionSlot(
          slot: 0,
          editable: false,
          alg: 0,
          nodiff: false,
          limitSoft: 0,
          limitHard: 0),
      DirectionSlot(
          slot: 1,
          editable: true,
          alg: 65,
          nodiff: true,
          limitSoft: 9000,
          limitHard: 9000),
      DirectionSlot(
          slot: 2,
          editable: true,
          alg: 66,
          nodiff: false,
          limitSoft: 9000,
          limitHard: 9000),
      DirectionSlot(
          slot: 3,
          editable: true,
          alg: 42,
          nodiff: false,
          limitSoft: 0,
          limitHard: 0),
      DirectionSlot(
          slot: 4,
          editable: true,
          alg: 68,
          nodiff: true,
          limitSoft: 0,
          limitHard: 0),
      DirectionSlot(
          slot: 5,
          editable: false,
          alg: 0,
          nodiff: false,
          limitSoft: 0,
          limitHard: 0)
    ],
  ),
  Plan(
    id: "megafon_spb_good",
    commandSetId: "megafon_spb",
    priority: 7,
    onlineMax: 5,
    addMax: 1,
    diffSlow: 5,
    diffMin: 61,
    iattMin: 12,
    iattMax: 20,
    iattSoft: 1,
    inAcdMin: 180,
    inAcdMax: 240,
    outAcdMin: 180,
    outAcdMax: 240,
    outInAns: 10,
    mayLimit: 5,
    monLimit: 3,
    msmLimit: 1,
    smsoutSoft: 1,
    smsoutHard: 1,
    sattSoft: 10,
    sattHard: 50,
    sattSoftDay: 10,
    sattHardDay: 3,
    sattSoftTotal: 100,
    sattHardTotal: 20,
    nospam: 1,
    canIn: true,
    canOut: true,
    canSout: true,
    notVip: true,
    capOk: true,
    capNew: true,
    capFail: false,
    forwarding: true,
    conn: true,
    rand: true,
    inWait: false,
    inSound: true,
    qualityFlags: {"VIP", "GOO", "NOR"},
    directions: [
      DirectionSlot(
          slot: 0,
          editable: false,
          alg: 0,
          nodiff: false,
          limitSoft: 0,
          limitHard: 0),
      DirectionSlot(
          slot: 1,
          editable: true,
          alg: 65,
          nodiff: false,
          limitSoft: 9000,
          limitHard: 9000),
      DirectionSlot(
          slot: 2,
          editable: true,
          alg: 42,
          nodiff: false,
          limitSoft: 9000,
          limitHard: 10000),
      DirectionSlot(
          slot: 3,
          editable: true,
          alg: 68,
          nodiff: false,
          limitSoft: 0,
          limitHard: 0),
      DirectionSlot(
          slot: 4,
          editable: true,
          alg: 68,
          nodiff: false,
          limitSoft: 0,
          limitHard: 0),
      DirectionSlot(
          slot: 5,
          editable: false,
          alg: 0,
          nodiff: false,
          limitSoft: 0,
          limitHard: 0)
    ],
  ),
  Plan(
    id: "megafon_spb_normal",
    commandSetId: "megafon_spb",
    priority: 6,
    onlineMax: 5,
    addMax: 1,
    diffSlow: 5,
    diffMin: 61,
    iattMin: 12,
    iattMax: 20,
    iattSoft: 1,
    inAcdMin: 180,
    inAcdMax: 180,
    outAcdMin: 180,
    outAcdMax: 240,
    outInAns: 10,
    mayLimit: 5,
    monLimit: 3,
    msmLimit: 1,
    smsoutSoft: 1,
    smsoutHard: 1,
    sattSoft: 10,
    sattHard: 50,
    sattSoftDay: 10,
    sattHardDay: 3,
    sattSoftTotal: 100,
    sattHardTotal: 20,
    nospam: 1,
    canIn: true,
    canOut: true,
    canSout: true,
    notVip: true,
    capOk: true,
    capNew: true,
    capFail: false,
    forwarding: true,
    conn: true,
    rand: true,
    inWait: false,
    inSound: true,
    qualityFlags: {"VIP", "GOO", "NOR", "NEW"},
    directions: [
      DirectionSlot(
          slot: 0,
          editable: false,
          alg: 0,
          nodiff: false,
          limitSoft: 0,
          limitHard: 0),
      DirectionSlot(
          slot: 1,
          editable: true,
          alg: 65,
          nodiff: false,
          limitSoft: 9000,
          limitHard: 10000),
      DirectionSlot(
          slot: 2,
          editable: true,
          alg: 66,
          nodiff: false,
          limitSoft: 9000,
          limitHard: 10000),
      DirectionSlot(
          slot: 3,
          editable: true,
          alg: 68,
          nodiff: false,
          limitSoft: 0,
          limitHard: 0),
      DirectionSlot(
          slot: 4,
          editable: true,
          alg: 100,
          nodiff: true,
          limitSoft: 9000,
          limitHard: 10000),
      DirectionSlot(
          slot: 5,
          editable: false,
          alg: 0,
          nodiff: false,
          limitSoft: 0,
          limitHard: 0)
    ],
  ),
  Plan(
    id: "megafon_spb_main",
    commandSetId: "megafon_spb",
    priority: 5,
    onlineMax: 5,
    addMax: 1,
    diffSlow: 5,
    diffMin: 61,
    iattMin: 20,
    iattMax: 30,
    iattSoft: 1,
    inAcdMin: 90,
    inAcdMax: 120,
    outAcdMin: 180,
    outAcdMax: 240,
    outInAns: 10,
    mayLimit: 5,
    monLimit: 3,
    msmLimit: 1,
    smsoutSoft: 1,
    smsoutHard: 1,
    sattSoft: 10,
    sattHard: 50,
    sattSoftDay: 10,
    sattHardDay: 3,
    sattSoftTotal: 100,
    sattHardTotal: 20,
    nospam: 1,
    canIn: true,
    canOut: true,
    canSout: true,
    notVip: true,
    capOk: true,
    capNew: true,
    capFail: true,
    forwarding: true,
    conn: false,
    rand: true,
    inWait: false,
    inSound: true,
    qualityFlags: {"VIP", "GOO", "NOR", "NEW"},
    directions: [
      DirectionSlot(
          slot: 0,
          editable: false,
          alg: 0,
          nodiff: false,
          limitSoft: 0,
          limitHard: 0),
      DirectionSlot(
          slot: 1,
          editable: true,
          alg: 65,
          nodiff: true,
          limitSoft: 9000,
          limitHard: 9000),
      DirectionSlot(
          slot: 2,
          editable: true,
          alg: 66,
          nodiff: false,
          limitSoft: 9000,
          limitHard: 9000),
      DirectionSlot(
          slot: 3,
          editable: true,
          alg: 42,
          nodiff: false,
          limitSoft: 0,
          limitHard: 0),
      DirectionSlot(
          slot: 4,
          editable: true,
          alg: 100,
          nodiff: true,
          limitSoft: 0,
          limitHard: 0),
      DirectionSlot(
          slot: 5,
          editable: false,
          alg: 0,
          nodiff: false,
          limitSoft: 0,
          limitHard: 0)
    ],
  ),
  Plan(
    id: "tele2_spb_last",
    commandSetId: "tele2_spb",
    proTag: "2",
    priority: 7,
    onlineMax: 5,
    addMax: 1,
    diffSlow: 5,
    diffMin: 21,
    iattMin: 999,
    iattMax: 999,
    iattSoft: 1,
    inAcdMin: 60,
    inAcdMax: 180,
    outAcdMin: 60,
    outAcdMax: 180,
    outInAns: 6,
    mayLimit: 0,
    monLimit: 4,
    msmLimit: 0,
    smsoutSoft: 50,
    smsoutHard: 90,
    sattSoft: 10,
    sattHard: 50,
    sattSoftDay: 10,
    sattHardDay: 90,
    sattSoftTotal: 100,
    sattHardTotal: 95,
    nospam: 2,
    canIn: true,
    canOut: true,
    canSout: true,
    notVip: true,
    capOk: true,
    capNew: true,
    capFail: true,
    forwarding: true,
    conn: false,
    rand: true,
    inWait: false,
    inSound: true,
    qualityFlags: {"VIP", "GOO", "NOR", "BAD", "NEW", "NOS", "BLO"},
    directions: [
      DirectionSlot(
          slot: 0,
          editable: false,
          alg: 0,
          nodiff: false,
          limitSoft: 0,
          limitHard: 0),
      DirectionSlot(
          slot: 1,
          editable: true,
          alg: 98,
          nodiff: true,
          limitSoft: 9000,
          limitHard: 10000),
      DirectionSlot(
          slot: 2,
          editable: true,
          alg: 80,
          nodiff: false,
          limitSoft: 9000,
          limitHard: 10000),
      DirectionSlot(
          slot: 3,
          editable: true,
          alg: 80,
          nodiff: false,
          limitSoft: 0,
          limitHard: 10000),
      DirectionSlot(
          slot: 4,
          editable: true,
          alg: 80,
          nodiff: false,
          limitSoft: 9000,
          limitHard: 0),
      DirectionSlot(
          slot: 5,
          editable: false,
          alg: 0,
          nodiff: false,
          limitSoft: 0,
          limitHard: 0)
    ],
  ),
  Plan(
    id: "tele2_spb_normal",
    commandSetId: "tele2_spb",
    proTag: "VIK",
    priority: 9,
    onlineMax: 5,
    addMax: 1,
    diffSlow: 5,
    diffMin: 20,
    iattMin: 999,
    iattMax: 999,
    iattSoft: 1,
    inAcdMin: 60,
    inAcdMax: 180,
    outAcdMin: 60,
    outAcdMax: 180,
    outInAns: 6,
    mayLimit: 0,
    monLimit: 4,
    msmLimit: 0,
    smsoutSoft: 50,
    smsoutHard: 90,
    sattSoft: 10,
    sattHard: 50,
    sattSoftDay: 10,
    sattHardDay: 3,
    sattSoftTotal: 100,
    sattHardTotal: 20,
    nospam: 2,
    canIn: true,
    canOut: true,
    canSout: true,
    notVip: true,
    capOk: true,
    capNew: true,
    capFail: true,
    forwarding: true,
    conn: true,
    rand: true,
    inWait: false,
    inSound: true,
    qualityFlags: {"VIP", "GOO", "NOR", "BAD", "NEW", "NOS", "ROB", "BLO"},
    directions: [
      DirectionSlot(
          slot: 0,
          editable: false,
          alg: 0,
          nodiff: false,
          limitSoft: 0,
          limitHard: 0),
      DirectionSlot(
          slot: 1,
          editable: true,
          alg: 66,
          nodiff: true,
          limitSoft: 9000,
          limitHard: 10000),
      DirectionSlot(
          slot: 2,
          editable: true,
          alg: 68,
          nodiff: false,
          limitSoft: 9000,
          limitHard: 10000),
      DirectionSlot(
          slot: 3,
          editable: true,
          alg: 68,
          nodiff: false,
          limitSoft: 0,
          limitHard: 0),
      DirectionSlot(
          slot: 4,
          editable: true,
          alg: 65,
          nodiff: false,
          limitSoft: 0,
          limitHard: 0),
      DirectionSlot(
          slot: 5,
          editable: false,
          alg: 0,
          nodiff: false,
          limitSoft: 0,
          limitHard: 0)
    ],
  ),
  Plan(
    id: "tele2_spb_main",
    commandSetId: "tele2_spb",
    proTag: "GUR",
    priority: 9,
    onlineMax: 5,
    addMax: 1,
    diffSlow: 5,
    diffMin: 20,
    iattMin: 999,
    iattMax: 999,
    iattSoft: 1,
    inAcdMin: 60,
    inAcdMax: 180,
    outAcdMin: 60,
    outAcdMax: 180,
    outInAns: 4,
    mayLimit: 0,
    monLimit: 4,
    msmLimit: 0,
    smsoutSoft: 0,
    smsoutHard: 90,
    sattSoft: 10,
    sattHard: 50,
    sattSoftDay: 10,
    sattHardDay: 3,
    sattSoftTotal: 100,
    sattHardTotal: 20,
    nospam: 1,
    canIn: true,
    canOut: true,
    canSout: true,
    notVip: true,
    capOk: true,
    capNew: true,
    capFail: true,
    forwarding: true,
    conn: true,
    rand: true,
    inWait: false,
    inSound: true,
    qualityFlags: {"VIP", "GOO", "NOR", "BAD", "NEW", "NOS", "ROB", "BLO"},
    directions: [
      DirectionSlot(
          slot: 0,
          editable: false,
          alg: 0,
          nodiff: false,
          limitSoft: 0,
          limitHard: 0),
      DirectionSlot(
          slot: 1,
          editable: true,
          alg: 42,
          nodiff: true,
          limitSoft: 9000,
          limitHard: 10000),
      DirectionSlot(
          slot: 2,
          editable: true,
          alg: 68,
          nodiff: false,
          limitSoft: 9000,
          limitHard: 10000),
      DirectionSlot(
          slot: 3,
          editable: true,
          alg: 68,
          nodiff: false,
          limitSoft: 0,
          limitHard: 0),
      DirectionSlot(
          slot: 4,
          editable: true,
          alg: 65,
          nodiff: false,
          limitSoft: 0,
          limitHard: 0),
      DirectionSlot(
          slot: 5,
          editable: false,
          alg: 0,
          nodiff: false,
          limitSoft: 0,
          limitHard: 0)
    ],
  ),
  Plan(
    id: "tele2_spb_bad",
    commandSetId: "tele2_spb",
    priority: 5,
    onlineMax: 5,
    addMax: 1,
    diffSlow: 5,
    diffMin: 50,
    iattMin: 5,
    iattMax: 999,
    iattSoft: 999,
    inAcdMin: 60,
    inAcdMax: 180,
    outAcdMin: 60,
    outAcdMax: 180,
    outInAns: 6,
    mayLimit: 0,
    monLimit: 2,
    msmLimit: 0,
    smsoutSoft: 50,
    smsoutHard: 90,
    sattSoft: 10,
    sattHard: 50,
    sattSoftDay: 10,
    sattHardDay: 3,
    sattSoftTotal: 100,
    sattHardTotal: 20,
    nospam: 1,
    canIn: true,
    canOut: true,
    canSout: true,
    notVip: true,
    capOk: true,
    capNew: true,
    capFail: true,
    forwarding: true,
    conn: true,
    rand: true,
    inWait: false,
    inSound: true,
    qualityFlags: {"VIP", "GOO", "NOR", "BAD", "NEW", "NOS"},
    directions: [
      DirectionSlot(
          slot: 0,
          editable: false,
          alg: 0,
          nodiff: false,
          limitSoft: 0,
          limitHard: 0),
      DirectionSlot(
          slot: 1,
          editable: true,
          alg: 66,
          nodiff: true,
          limitSoft: 9000,
          limitHard: 10000),
      DirectionSlot(
          slot: 2,
          editable: true,
          alg: 68,
          nodiff: false,
          limitSoft: 9000,
          limitHard: 10000),
      DirectionSlot(
          slot: 3,
          editable: true,
          alg: 68,
          nodiff: false,
          limitSoft: 0,
          limitHard: 0),
      DirectionSlot(
          slot: 4,
          editable: true,
          alg: 42,
          nodiff: false,
          limitSoft: 9000,
          limitHard: 0),
      DirectionSlot(
          slot: 5,
          editable: false,
          alg: 0,
          nodiff: false,
          limitSoft: 0,
          limitHard: 0)
    ],
  ),
  Plan(
    id: "mts_spb_good",
    commandSetId: "mts_spb",
    priority: 8,
    onlineMax: 5,
    addMax: 1,
    diffSlow: 5,
    diffMin: 7200,
    iattMin: 3,
    iattMax: 5,
    iattSoft: 1,
    inAcdMin: 60,
    inAcdMax: 180,
    outAcdMin: 60,
    outAcdMax: 180,
    outInAns: 4,
    mayLimit: 5,
    monLimit: 2,
    msmLimit: 1,
    smsoutSoft: 0,
    smsoutHard: 1,
    sattSoft: 10,
    sattHard: 50,
    sattSoftDay: 10,
    sattHardDay: 3,
    sattSoftTotal: 100,
    sattHardTotal: 20,
    nospam: 1,
    canIn: true,
    canOut: true,
    canSout: true,
    notVip: true,
    capOk: true,
    capNew: true,
    capFail: false,
    forwarding: true,
    conn: true,
    rand: true,
    inWait: false,
    inSound: true,
    qualityFlags: {"VIP", "GOO"},
    directions: [
      DirectionSlot(
          slot: 0,
          editable: false,
          alg: 0,
          nodiff: false,
          limitSoft: 0,
          limitHard: 0),
      DirectionSlot(
          slot: 1,
          editable: true,
          alg: 68,
          nodiff: false,
          limitSoft: 9000,
          limitHard: 10000),
      DirectionSlot(
          slot: 2,
          editable: true,
          alg: 68,
          nodiff: false,
          limitSoft: 9000,
          limitHard: 10000),
      DirectionSlot(
          slot: 3,
          editable: true,
          alg: 68,
          nodiff: false,
          limitSoft: 9000,
          limitHard: 10000),
      DirectionSlot(
          slot: 4,
          editable: true,
          alg: 68,
          nodiff: false,
          limitSoft: 9000,
          limitHard: 10000),
      DirectionSlot(
          slot: 5,
          editable: false,
          alg: 0,
          nodiff: false,
          limitSoft: 0,
          limitHard: 0)
    ],
  ),
  Plan(
    id: "beeline_spb_max",
    commandSetId: "beeline_spb",
    priority: 9,
    onlineMax: 5,
    addMax: 1,
    diffSlow: 5,
    diffMin: 10,
    iattMin: 5,
    iattMax: 7,
    iattSoft: 1,
    inAcdMin: 60,
    inAcdMax: 180,
    outAcdMin: 60,
    outAcdMax: 180,
    outInAns: 6,
    mayLimit: 5,
    monLimit: 2,
    msmLimit: 1,
    smsoutSoft: 0,
    smsoutHard: 1,
    sattSoft: 10,
    sattHard: 50,
    sattSoftDay: 10,
    sattHardDay: 3,
    sattSoftTotal: 100,
    sattHardTotal: 20,
    nospam: 1,
    canIn: true,
    canOut: true,
    canSout: true,
    notVip: true,
    capOk: true,
    capNew: true,
    capFail: false,
    forwarding: false,
    conn: true,
    rand: true,
    inWait: false,
    inSound: true,
    qualityFlags: {"VIP", "BAD", "NEW", "NOS"},
    directions: [
      DirectionSlot(
          slot: 0,
          editable: false,
          alg: 0,
          nodiff: false,
          limitSoft: 0,
          limitHard: 0),
      DirectionSlot(
          slot: 1,
          editable: true,
          alg: 68,
          nodiff: false,
          limitSoft: 9000,
          limitHard: 10000),
      DirectionSlot(
          slot: 2,
          editable: true,
          alg: 68,
          nodiff: false,
          limitSoft: 9000,
          limitHard: 10000),
      DirectionSlot(
          slot: 3,
          editable: true,
          alg: 68,
          nodiff: false,
          limitSoft: 9000,
          limitHard: 10000),
      DirectionSlot(
          slot: 4,
          editable: true,
          alg: 42,
          nodiff: false,
          limitSoft: 9000,
          limitHard: 10000),
      DirectionSlot(
          slot: 5,
          editable: false,
          alg: 0,
          nodiff: false,
          limitSoft: 0,
          limitHard: 0)
    ],
  ),
  Plan(
    id: "beeline_spb_new",
    commandSetId: "beeline_spb",
    priority: 6,
    onlineMax: 5,
    addMax: 1,
    diffSlow: 5,
    diffMin: 100,
    iattMin: 5,
    iattMax: 8,
    iattSoft: 1,
    inAcdMin: 60,
    inAcdMax: 180,
    outAcdMin: 60,
    outAcdMax: 180,
    outInAns: 5,
    mayLimit: 5,
    monLimit: 2,
    msmLimit: 1,
    smsoutSoft: 0,
    smsoutHard: 1,
    sattSoft: 10,
    sattHard: 50,
    sattSoftDay: 10,
    sattHardDay: 3,
    sattSoftTotal: 100,
    sattHardTotal: 20,
    nospam: 1,
    canIn: true,
    canOut: true,
    canSout: true,
    notVip: true,
    capOk: true,
    capNew: true,
    capFail: false,
    forwarding: true,
    conn: true,
    rand: true,
    inWait: false,
    inSound: true,
    qualityFlags: {"VIP", "GOO", "NOR", "BAD", "NEW"},
    directions: [
      DirectionSlot(
          slot: 0,
          editable: false,
          alg: 0,
          nodiff: false,
          limitSoft: 0,
          limitHard: 0),
      DirectionSlot(
          slot: 1,
          editable: true,
          alg: 68,
          nodiff: false,
          limitSoft: 9000,
          limitHard: 10000),
      DirectionSlot(
          slot: 2,
          editable: true,
          alg: 68,
          nodiff: false,
          limitSoft: 9000,
          limitHard: 10000),
      DirectionSlot(
          slot: 3,
          editable: true,
          alg: 68,
          nodiff: false,
          limitSoft: 9000,
          limitHard: 10000),
      DirectionSlot(
          slot: 4,
          editable: true,
          alg: 42,
          nodiff: false,
          limitSoft: 9000,
          limitHard: 10000),
      DirectionSlot(
          slot: 5,
          editable: false,
          alg: 0,
          nodiff: false,
          limitSoft: 0,
          limitHard: 0)
    ],
  ),
  Plan(
    id: "beeline_spb_old",
    commandSetId: "beeline_spb",
    priority: 5,
    onlineMax: 5,
    addMax: 1,
    diffSlow: 5,
    diffMin: 120,
    iattMin: 6,
    iattMax: 9,
    iattSoft: 1,
    inAcdMin: 60,
    inAcdMax: 180,
    outAcdMin: 60,
    outAcdMax: 180,
    outInAns: 8,
    mayLimit: 5,
    monLimit: 2,
    msmLimit: 1,
    smsoutSoft: 0,
    smsoutHard: 1,
    sattSoft: 10,
    sattHard: 50,
    sattSoftDay: 10,
    sattHardDay: 3,
    sattSoftTotal: 100,
    sattHardTotal: 20,
    nospam: 1,
    canIn: true,
    canOut: true,
    canSout: true,
    notVip: true,
    capOk: true,
    capNew: true,
    capFail: false,
    forwarding: true,
    conn: true,
    rand: true,
    inWait: false,
    inSound: true,
    qualityFlags: {"VIP", "GOO", "NOR", "NEW", "NOS"},
    directions: [
      DirectionSlot(
          slot: 0,
          editable: false,
          alg: 0,
          nodiff: false,
          limitSoft: 0,
          limitHard: 0),
      DirectionSlot(
          slot: 1,
          editable: true,
          alg: 68,
          nodiff: false,
          limitSoft: 9000,
          limitHard: 10000),
      DirectionSlot(
          slot: 2,
          editable: true,
          alg: 68,
          nodiff: false,
          limitSoft: 9000,
          limitHard: 10000),
      DirectionSlot(
          slot: 3,
          editable: true,
          alg: 68,
          nodiff: false,
          limitSoft: 9000,
          limitHard: 10000),
      DirectionSlot(
          slot: 4,
          editable: true,
          alg: 42,
          nodiff: false,
          limitSoft: 9000,
          limitHard: 10000),
      DirectionSlot(
          slot: 5,
          editable: false,
          alg: 0,
          nodiff: false,
          limitSoft: 0,
          limitHard: 0)
    ],
  ),
  Plan(
    id: "megafon_spb_max_safe",
    commandSetId: "megafon_spb",
    priority: 8,
    onlineMax: 5,
    addMax: 1,
    diffSlow: 5,
    diffMin: 6000,
    iattMin: 50,
    iattMax: 150,
    iattSoft: 1,
    inAcdMin: 60,
    inAcdMax: 180,
    outAcdMin: 60,
    outAcdMax: 180,
    outInAns: 6,
    mayLimit: 5,
    monLimit: 2,
    msmLimit: 1,
    smsoutSoft: 0,
    smsoutHard: 1,
    sattSoft: 10,
    sattHard: 50,
    sattSoftDay: 10,
    sattHardDay: 3,
    sattSoftTotal: 100,
    sattHardTotal: 20,
    nospam: 1,
    canIn: true,
    canOut: true,
    canSout: true,
    notVip: true,
    capOk: true,
    capNew: true,
    capFail: false,
    forwarding: true,
    conn: true,
    rand: true,
    inWait: false,
    inSound: true,
    qualityFlags: {"VIP", "GOO", "NEW"},
    directions: [
      DirectionSlot(
          slot: 0,
          editable: false,
          alg: 0,
          nodiff: false,
          limitSoft: 0,
          limitHard: 0),
      DirectionSlot(
          slot: 1,
          editable: true,
          alg: 68,
          nodiff: false,
          limitSoft: 9000,
          limitHard: 10000),
      DirectionSlot(
          slot: 2,
          editable: true,
          alg: 42,
          nodiff: false,
          limitSoft: 9000,
          limitHard: 10000),
      DirectionSlot(
          slot: 3,
          editable: true,
          alg: 42,
          nodiff: false,
          limitSoft: 9000,
          limitHard: 10000),
      DirectionSlot(
          slot: 4,
          editable: true,
          alg: 42,
          nodiff: false,
          limitSoft: 9000,
          limitHard: 10000),
      DirectionSlot(
          slot: 5,
          editable: false,
          alg: 0,
          nodiff: false,
          limitSoft: 0,
          limitHard: 0)
    ],
  ),
  Plan(
    id: "megafon_spb_max",
    commandSetId: "megafon_spb",
    priority: 4,
    onlineMax: 5,
    addMax: 1,
    diffSlow: 5,
    diffMin: 60,
    iattMin: 5,
    iattMax: 150,
    iattSoft: 1,
    inAcdMin: 60,
    inAcdMax: 180,
    outAcdMin: 60,
    outAcdMax: 180,
    outInAns: 6,
    mayLimit: 5,
    monLimit: 2,
    msmLimit: 1,
    smsoutSoft: 0,
    smsoutHard: 1,
    sattSoft: 10,
    sattHard: 50,
    sattSoftDay: 10,
    sattHardDay: 3,
    sattSoftTotal: 100,
    sattHardTotal: 20,
    nospam: 1,
    canIn: true,
    canOut: true,
    canSout: true,
    notVip: true,
    capOk: true,
    capNew: true,
    capFail: false,
    forwarding: true,
    conn: true,
    rand: true,
    inWait: false,
    inSound: true,
    qualityFlags: {"VIP", "GOO", "NOR", "BAD", "NEW", "NOS", "ROB", "BLO"},
    directions: [
      DirectionSlot(
          slot: 0,
          editable: false,
          alg: 0,
          nodiff: false,
          limitSoft: 0,
          limitHard: 0),
      DirectionSlot(
          slot: 1,
          editable: true,
          alg: 68,
          nodiff: false,
          limitSoft: 9000,
          limitHard: 10000),
      DirectionSlot(
          slot: 2,
          editable: true,
          alg: 42,
          nodiff: false,
          limitSoft: 9000,
          limitHard: 10000),
      DirectionSlot(
          slot: 3,
          editable: true,
          alg: 42,
          nodiff: false,
          limitSoft: 9000,
          limitHard: 10000),
      DirectionSlot(
          slot: 4,
          editable: true,
          alg: 42,
          nodiff: false,
          limitSoft: 9000,
          limitHard: 10000),
      DirectionSlot(
          slot: 5,
          editable: false,
          alg: 0,
          nodiff: false,
          limitSoft: 0,
          limitHard: 0)
    ],
  ),
  Plan(
    id: "megafon_spb_bad",
    commandSetId: "megafon_spb",
    priority: 7,
    onlineMax: 5,
    addMax: 1,
    diffSlow: 5,
    diffMin: 3999,
    iattMin: 10,
    iattMax: 100,
    iattSoft: 1,
    inAcdMin: 60,
    inAcdMax: 180,
    outAcdMin: 60,
    outAcdMax: 180,
    outInAns: 6,
    mayLimit: 5,
    monLimit: 2,
    msmLimit: 1,
    smsoutSoft: 0,
    smsoutHard: 1,
    sattSoft: 10,
    sattHard: 50,
    sattSoftDay: 10,
    sattHardDay: 3,
    sattSoftTotal: 100,
    sattHardTotal: 20,
    nospam: 1,
    canIn: true,
    canOut: true,
    canSout: true,
    notVip: true,
    capOk: true,
    capNew: true,
    capFail: false,
    forwarding: true,
    conn: true,
    rand: true,
    inWait: false,
    inSound: true,
    qualityFlags: {"VIP", "GOO"},
    directions: [
      DirectionSlot(
          slot: 0,
          editable: false,
          alg: 0,
          nodiff: false,
          limitSoft: 0,
          limitHard: 0),
      DirectionSlot(
          slot: 1,
          editable: true,
          alg: 42,
          nodiff: false,
          limitSoft: 0,
          limitHard: 0),
      DirectionSlot(
          slot: 2,
          editable: true,
          alg: 42,
          nodiff: false,
          limitSoft: 0,
          limitHard: 10000),
      DirectionSlot(
          slot: 3,
          editable: true,
          alg: 42,
          nodiff: false,
          limitSoft: 9000,
          limitHard: 10000),
      DirectionSlot(
          slot: 4,
          editable: true,
          alg: 42,
          nodiff: false,
          limitSoft: 0,
          limitHard: 10000),
      DirectionSlot(
          slot: 5,
          editable: false,
          alg: 0,
          nodiff: false,
          limitSoft: 0,
          limitHard: 0)
    ],
  ),
  Plan(
    id: "megafon_msk_good",
    commandSetId: "megafon_msk",
    priority: 5,
    onlineMax: 5,
    addMax: 1,
    diffSlow: 5,
    diffMin: 180,
    iattMin: 10,
    iattMax: 100,
    iattSoft: 1,
    inAcdMin: 60,
    inAcdMax: 180,
    outAcdMin: 60,
    outAcdMax: 180,
    outInAns: 6,
    mayLimit: 5,
    monLimit: 2,
    msmLimit: 1,
    smsoutSoft: 0,
    smsoutHard: 1,
    sattSoft: 10,
    sattHard: 50,
    sattSoftDay: 10,
    sattHardDay: 3,
    sattSoftTotal: 100,
    sattHardTotal: 20,
    nospam: 1,
    canIn: true,
    canOut: true,
    canSout: true,
    notVip: true,
    capOk: true,
    capNew: true,
    capFail: false,
    forwarding: true,
    conn: true,
    rand: true,
    inWait: false,
    inSound: true,
    qualityFlags: {"VIP", "GOO", "NOR"},
    directions: [
      DirectionSlot(
          slot: 0,
          editable: false,
          alg: 0,
          nodiff: false,
          limitSoft: 0,
          limitHard: 0),
      DirectionSlot(
          slot: 1,
          editable: true,
          alg: 42,
          nodiff: false,
          limitSoft: 0,
          limitHard: 0),
      DirectionSlot(
          slot: 2,
          editable: true,
          alg: 42,
          nodiff: false,
          limitSoft: 0,
          limitHard: 10000),
      DirectionSlot(
          slot: 3,
          editable: true,
          alg: 42,
          nodiff: false,
          limitSoft: 0,
          limitHard: 10000),
      DirectionSlot(
          slot: 4,
          editable: true,
          alg: 42,
          nodiff: false,
          limitSoft: 0,
          limitHard: 10000),
      DirectionSlot(
          slot: 5,
          editable: false,
          alg: 0,
          nodiff: false,
          limitSoft: 0,
          limitHard: 0)
    ],
  ),
  Plan(
    id: "megafon_msk_bad",
    commandSetId: "megafon_msk",
    priority: 5,
    onlineMax: 5,
    addMax: 1,
    diffSlow: 5,
    diffMin: 40,
    iattMin: 5,
    iattMax: 100,
    iattSoft: 1,
    inAcdMin: 60,
    inAcdMax: 180,
    outAcdMin: 60,
    outAcdMax: 180,
    outInAns: 6,
    mayLimit: 5,
    monLimit: 2,
    msmLimit: 1,
    smsoutSoft: 0,
    smsoutHard: 1,
    sattSoft: 10,
    sattHard: 50,
    sattSoftDay: 10,
    sattHardDay: 3,
    sattSoftTotal: 100,
    sattHardTotal: 20,
    nospam: 1,
    canIn: true,
    canOut: true,
    canSout: true,
    notVip: true,
    capOk: true,
    capNew: true,
    capFail: false,
    forwarding: true,
    conn: true,
    rand: true,
    inWait: false,
    inSound: true,
    qualityFlags: {"VIP", "BAD"},
    directions: [
      DirectionSlot(
          slot: 0,
          editable: false,
          alg: 0,
          nodiff: false,
          limitSoft: 0,
          limitHard: 0),
      DirectionSlot(
          slot: 1,
          editable: true,
          alg: 42,
          nodiff: false,
          limitSoft: 0,
          limitHard: 0),
      DirectionSlot(
          slot: 2,
          editable: true,
          alg: 42,
          nodiff: false,
          limitSoft: 0,
          limitHard: 10000),
      DirectionSlot(
          slot: 3,
          editable: true,
          alg: 42,
          nodiff: false,
          limitSoft: 0,
          limitHard: 10000),
      DirectionSlot(
          slot: 4,
          editable: true,
          alg: 42,
          nodiff: false,
          limitSoft: 0,
          limitHard: 10000),
      DirectionSlot(
          slot: 5,
          editable: false,
          alg: 0,
          nodiff: false,
          limitSoft: 0,
          limitHard: 0)
    ],
  ),
  Plan(
    id: "megafon_msk_main",
    commandSetId: "megafon_msk",
    priority: 5,
    onlineMax: 5,
    addMax: 1,
    diffSlow: 5,
    diffMin: 40,
    iattMin: 10,
    iattMax: 100,
    iattSoft: 1,
    inAcdMin: 60,
    inAcdMax: 180,
    outAcdMin: 60,
    outAcdMax: 180,
    outInAns: 6,
    mayLimit: 5,
    monLimit: 2,
    msmLimit: 1,
    smsoutSoft: 0,
    smsoutHard: 1,
    sattSoft: 10,
    sattHard: 50,
    sattSoftDay: 10,
    sattHardDay: 3,
    sattSoftTotal: 100,
    sattHardTotal: 20,
    nospam: 1,
    canIn: true,
    canOut: true,
    canSout: true,
    notVip: true,
    capOk: true,
    capNew: true,
    capFail: false,
    forwarding: true,
    conn: true,
    rand: true,
    inWait: false,
    inSound: true,
    qualityFlags: {"VIP", "GOO", "NOR", "BAD", "NEW", "NOS"},
    directions: [
      DirectionSlot(
          slot: 0,
          editable: false,
          alg: 0,
          nodiff: false,
          limitSoft: 0,
          limitHard: 0),
      DirectionSlot(
          slot: 1,
          editable: true,
          alg: 42,
          nodiff: false,
          limitSoft: 0,
          limitHard: 0),
      DirectionSlot(
          slot: 2,
          editable: true,
          alg: 42,
          nodiff: false,
          limitSoft: 0,
          limitHard: 10000),
      DirectionSlot(
          slot: 3,
          editable: true,
          alg: 42,
          nodiff: false,
          limitSoft: 0,
          limitHard: 10000),
      DirectionSlot(
          slot: 4,
          editable: true,
          alg: 42,
          nodiff: false,
          limitSoft: 0,
          limitHard: 10000),
      DirectionSlot(
          slot: 5,
          editable: false,
          alg: 0,
          nodiff: false,
          limitSoft: 0,
          limitHard: 0)
    ],
  ),
  Plan(
    id: "beeline_spb_new_safe",
    commandSetId: "beeline_spb",
    priority: 7,
    onlineMax: 5,
    addMax: 1,
    diffSlow: 5,
    diffMin: 60,
    iattMin: 3,
    iattMax: 5,
    iattSoft: 1,
    inAcdMin: 60,
    inAcdMax: 180,
    outAcdMin: 60,
    outAcdMax: 180,
    outInAns: 5,
    mayLimit: 5,
    monLimit: 2,
    msmLimit: 1,
    smsoutSoft: 0,
    smsoutHard: 1,
    sattSoft: 10,
    sattHard: 50,
    sattSoftDay: 10,
    sattHardDay: 3,
    sattSoftTotal: 100,
    sattHardTotal: 20,
    nospam: 1,
    canIn: true,
    canOut: true,
    canSout: true,
    notVip: true,
    capOk: true,
    capNew: true,
    capFail: false,
    forwarding: true,
    conn: true,
    rand: true,
    inWait: false,
    inSound: true,
    qualityFlags: {"VIP", "GOO"},
    directions: [
      DirectionSlot(
          slot: 0,
          editable: false,
          alg: 0,
          nodiff: false,
          limitSoft: 0,
          limitHard: 0),
      DirectionSlot(
          slot: 1,
          editable: true,
          alg: 42,
          nodiff: false,
          limitSoft: 9000,
          limitHard: 10000),
      DirectionSlot(
          slot: 2,
          editable: true,
          alg: 68,
          nodiff: false,
          limitSoft: 9000,
          limitHard: 10000),
      DirectionSlot(
          slot: 3,
          editable: true,
          alg: 68,
          nodiff: false,
          limitSoft: 9000,
          limitHard: 10000),
      DirectionSlot(
          slot: 4,
          editable: true,
          alg: 42,
          nodiff: false,
          limitSoft: 9000,
          limitHard: 10000),
      DirectionSlot(
          slot: 5,
          editable: false,
          alg: 0,
          nodiff: false,
          limitSoft: 0,
          limitHard: 0)
    ],
  ),
  Plan(
    id: "mts_spb_safe",
    commandSetId: "mts_spb",
    priority: 9,
    onlineMax: 5,
    addMax: 1,
    diffSlow: 5,
    diffMin: 300,
    iattMin: 5,
    iattMax: 15,
    iattSoft: 1,
    inAcdMin: 60,
    inAcdMax: 180,
    outAcdMin: 60,
    outAcdMax: 180,
    outInAns: 6,
    mayLimit: 5,
    monLimit: 2,
    msmLimit: 1,
    smsoutSoft: 0,
    smsoutHard: 1,
    sattSoft: 10,
    sattHard: 50,
    sattSoftDay: 10,
    sattHardDay: 3,
    sattSoftTotal: 100,
    sattHardTotal: 20,
    nospam: 1,
    canIn: true,
    canOut: true,
    canSout: true,
    notVip: true,
    capOk: true,
    capNew: false,
    capFail: false,
    forwarding: true,
    conn: true,
    rand: true,
    inWait: false,
    inSound: true,
    qualityFlags: {"VIP", "GOO"},
    directions: [
      DirectionSlot(
          slot: 0,
          editable: false,
          alg: 0,
          nodiff: false,
          limitSoft: 0,
          limitHard: 0),
      DirectionSlot(
          slot: 1,
          editable: true,
          alg: 42,
          nodiff: false,
          limitSoft: 9000,
          limitHard: 10000),
      DirectionSlot(
          slot: 2,
          editable: true,
          alg: 68,
          nodiff: false,
          limitSoft: 9000,
          limitHard: 10000),
      DirectionSlot(
          slot: 3,
          editable: true,
          alg: 68,
          nodiff: false,
          limitSoft: 9000,
          limitHard: 10000),
      DirectionSlot(
          slot: 4,
          editable: true,
          alg: 42,
          nodiff: false,
          limitSoft: 9000,
          limitHard: 10000),
      DirectionSlot(
          slot: 5,
          editable: false,
          alg: 0,
          nodiff: false,
          limitSoft: 0,
          limitHard: 0)
    ],
  ),
  Plan(
    id: "mts_spb_60min",
    commandSetId: "mts_spb",
    priority: 9,
    onlineMax: 5,
    addMax: 1,
    diffSlow: 5,
    diffMin: 120,
    iattMin: 5,
    iattMax: 15,
    iattSoft: 1,
    inAcdMin: 60,
    inAcdMax: 180,
    outAcdMin: 60,
    outAcdMax: 180,
    outInAns: 6,
    mayLimit: 5,
    monLimit: 2,
    msmLimit: 1,
    smsoutSoft: 0,
    smsoutHard: 1,
    sattSoft: 10,
    sattHard: 50,
    sattSoftDay: 10,
    sattHardDay: 3,
    sattSoftTotal: 100,
    sattHardTotal: 20,
    nospam: 1,
    canIn: true,
    canOut: true,
    canSout: true,
    notVip: true,
    capOk: true,
    capNew: true,
    capFail: false,
    forwarding: true,
    conn: true,
    rand: true,
    inWait: false,
    inSound: true,
    qualityFlags: {"VIP", "GOO"},
    directions: [
      DirectionSlot(
          slot: 0,
          editable: false,
          alg: 0,
          nodiff: false,
          limitSoft: 0,
          limitHard: 0),
      DirectionSlot(
          slot: 1,
          editable: true,
          alg: 68,
          nodiff: false,
          limitSoft: 9000,
          limitHard: 10000),
      DirectionSlot(
          slot: 2,
          editable: true,
          alg: 68,
          nodiff: false,
          limitSoft: 9000,
          limitHard: 10000),
      DirectionSlot(
          slot: 3,
          editable: true,
          alg: 68,
          nodiff: false,
          limitSoft: 3480,
          limitHard: 10000),
      DirectionSlot(
          slot: 4,
          editable: true,
          alg: 42,
          nodiff: false,
          limitSoft: 9000,
          limitHard: 10000),
      DirectionSlot(
          slot: 5,
          editable: false,
          alg: 0,
          nodiff: false,
          limitSoft: 0,
          limitHard: 0)
    ],
  ),
  Plan(
    id: "tele2_spb_new",
    commandSetId: "tele2_spb",
    priority: 5,
    onlineMax: 5,
    addMax: 1,
    diffSlow: 5,
    diffMin: 40,
    iattMin: 4,
    iattMax: 10,
    iattSoft: 1,
    inAcdMin: 60,
    inAcdMax: 180,
    outAcdMin: 60,
    outAcdMax: 180,
    outInAns: 6,
    mayLimit: 5,
    monLimit: 2,
    msmLimit: 1,
    smsoutSoft: 0,
    smsoutHard: 1,
    sattSoft: 10,
    sattHard: 50,
    sattSoftDay: 10,
    sattHardDay: 3,
    sattSoftTotal: 100,
    sattHardTotal: 20,
    nospam: 1,
    canIn: true,
    canOut: true,
    canSout: true,
    notVip: true,
    capOk: true,
    capNew: true,
    capFail: false,
    forwarding: true,
    conn: true,
    rand: true,
    inWait: false,
    inSound: true,
    qualityFlags: {"VIP", "GOO", "NOR", "BAD", "NOS"},
    directions: [
      DirectionSlot(
          slot: 0,
          editable: false,
          alg: 0,
          nodiff: false,
          limitSoft: 0,
          limitHard: 0),
      DirectionSlot(
          slot: 1,
          editable: true,
          alg: 68,
          nodiff: false,
          limitSoft: 9000,
          limitHard: 10000),
      DirectionSlot(
          slot: 2,
          editable: true,
          alg: 68,
          nodiff: false,
          limitSoft: 9000,
          limitHard: 10000),
      DirectionSlot(
          slot: 3,
          editable: true,
          alg: 42,
          nodiff: false,
          limitSoft: 3480,
          limitHard: 3600),
      DirectionSlot(
          slot: 4,
          editable: true,
          alg: 68,
          nodiff: false,
          limitSoft: 9000,
          limitHard: 10000),
      DirectionSlot(
          slot: 5,
          editable: false,
          alg: 0,
          nodiff: false,
          limitSoft: 0,
          limitHard: 0)
    ],
  ),
  Plan(
    id: "tele2_spb_60min",
    commandSetId: "tele2_spb",
    priority: 9,
    onlineMax: 5,
    addMax: 1,
    diffSlow: 5,
    diffMin: 300,
    iattMin: 5,
    iattMax: 15,
    iattSoft: 1,
    inAcdMin: 60,
    inAcdMax: 180,
    outAcdMin: 60,
    outAcdMax: 180,
    outInAns: 6,
    mayLimit: 5,
    monLimit: 2,
    msmLimit: 1,
    smsoutSoft: 0,
    smsoutHard: 1,
    sattSoft: 10,
    sattHard: 50,
    sattSoftDay: 10,
    sattHardDay: 3,
    sattSoftTotal: 100,
    sattHardTotal: 20,
    nospam: 1,
    canIn: true,
    canOut: true,
    canSout: true,
    notVip: true,
    capOk: true,
    capNew: true,
    capFail: false,
    forwarding: true,
    conn: true,
    rand: true,
    inWait: false,
    inSound: true,
    timeWorkWake: 10,
    timeWorkSleep: 21,
    timeHolidayWake: 10,
    timeHolidaySleep: 21,
    qualityFlags: {"VIP", "GOO"},
    directions: [
      DirectionSlot(
          slot: 0,
          editable: false,
          alg: 0,
          nodiff: false,
          limitSoft: 0,
          limitHard: 0),
      DirectionSlot(
          slot: 1,
          editable: true,
          alg: 68,
          nodiff: false,
          limitSoft: 9000,
          limitHard: 10000),
      DirectionSlot(
          slot: 2,
          editable: true,
          alg: 68,
          nodiff: false,
          limitSoft: 9000,
          limitHard: 10000),
      DirectionSlot(
          slot: 3,
          editable: true,
          alg: 68,
          nodiff: false,
          limitSoft: 3480,
          limitHard: 3600),
      DirectionSlot(
          slot: 4,
          editable: true,
          alg: 68,
          nodiff: false,
          limitSoft: 9000,
          limitHard: 10000),
      DirectionSlot(
          slot: 5,
          editable: false,
          alg: 0,
          nodiff: false,
          limitSoft: 0,
          limitHard: 0)
    ],
  ),
];
